zeebe.client:
#  broker.gatewayAddress: 127.0.0.1:26500
  broker.gatewayAddress: 192.168.1.142:26500
  security.plaintext: true
  worker.threads: 15
  worker.maxJobsActive: 1000

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: "*"